### ISSUE TITLE
Latest cloud update provides type property for relationships

### ISSUE THREAD

**Issue by rassilon** [JamaSoftware/RestClient#22]
https://github.com/JamaSoftware/RestClient/blob/0091bb2c4d2c9e1e5cae982c6d0b979d6bfbb271/src/main/java/com/jamasoftware/services/restclient/json/SimpleJsonDeserializer.java#L54

This won't get triggerd any longer with the latest update to Jama cloud hosted instances.

type now returns as "relationships".

Fyi,
Bill

**Comment by jmauersberger** [comment]
Indeed, latest update broke this Java library, is anyone working on that issue?
If not, is there any link to the API change that caused this issue so we may at least fix it on our own?

Thanks in advance
Jan

**Comment by JasonBrownPDX** [comment]
This looks like a small fix for any developer. They just need to fork the code. And make the adjustments

In the past month or so, we added a Restful non breaking change- adding a “type” field to the Relationship object. The client uses this type field to determine which type it is.

Before, no type existed on relationships, so the client was hard coded (back when it was written) to check if it was null, then check for another field to verify that it is a relationship then serialize it. Now that the API has a type on relationships, this no longer works. To get it to work you just need to check if type is “relationship” instead of null

You may want to consider leaving the some of the old code so that the client is backwards compatible.

**Comment by jmauersberger** [comment]
Ok, will fix it in a fork and ask for reintegration later

**Comment by nmchale-jama** [comment]
This issue is resolved in PR#23

Thank you to those who contributed to the resolution.
